project_id = "hthiaombwjumhkenasjt"

[functions.generate-summary]
verify_jwt = false

[functions.ai-post-analysis]
verify_jwt = false

[functions.ai-conversation-starters]
verify_jwt = false

[functions.ai-comment-reply]
verify_jwt = false