// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hthiaombwjumhkenasjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0aGlhb21id2p1bWhrZW5hc2p0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAzNTgxMTEsImV4cCI6MjA3NTkzNDExMX0.YQYHfT7FqXaIUIcAeqigcraAOzRuQMDb7lcbYVzunlw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});